// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repo/alert_contact.go

// Package testmocks is a generated GoMock package.
package testmocks

import (
	alert "WatchTower/internal/domain/entity/alert_contact"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockAlertContactRepository is a mock of AlertContactRepository interface.
type MockAlertContactRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAlertContactRepositoryMockRecorder
}

// MockAlertContactRepositoryMockRecorder is the mock recorder for MockAlertContactRepository.
type MockAlertContactRepositoryMockRecorder struct {
	mock *MockAlertContactRepository
}

// NewMockAlertContactRepository creates a new mock instance.
func NewMockAlertContactRepository(ctrl *gomock.Controller) *MockAlertContactRepository {
	mock := &MockAlertContactRepository{ctrl: ctrl}
	mock.recorder = &MockAlertContactRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlertContactRepository) EXPECT() *MockAlertContactRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAlertContactRepository) Create(ctx context.Context, contact *alert.Contact) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, contact)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAlertContactRepositoryMockRecorder) Create(ctx, contact interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAlertContactRepository)(nil).Create), ctx, contact)
}

// DeleteByID mocks base method.
func (m *MockAlertContactRepository) DeleteByID(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockAlertContactRepositoryMockRecorder) DeleteByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockAlertContactRepository)(nil).DeleteByID), ctx, id)
}

// Disable mocks base method.
func (m *MockAlertContactRepository) Disable(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disable", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Disable indicates an expected call of Disable.
func (mr *MockAlertContactRepositoryMockRecorder) Disable(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disable", reflect.TypeOf((*MockAlertContactRepository)(nil).Disable), ctx, id)
}

// Enable mocks base method.
func (m *MockAlertContactRepository) Enable(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enable", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enable indicates an expected call of Enable.
func (mr *MockAlertContactRepositoryMockRecorder) Enable(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enable", reflect.TypeOf((*MockAlertContactRepository)(nil).Enable), ctx, id)
}

// GetByID mocks base method.
func (m *MockAlertContactRepository) GetByID(ctx context.Context, id uuid.UUID) (*alert.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*alert.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAlertContactRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAlertContactRepository)(nil).GetByID), ctx, id)
}

// GetByIDBulk mocks base method.
func (m *MockAlertContactRepository) GetByIDBulk(ctx context.Context, ids []uuid.UUID) ([]alert.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDBulk", ctx, ids)
	ret0, _ := ret[0].([]alert.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDBulk indicates an expected call of GetByIDBulk.
func (mr *MockAlertContactRepositoryMockRecorder) GetByIDBulk(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDBulk", reflect.TypeOf((*MockAlertContactRepository)(nil).GetByIDBulk), ctx, ids)
}

// GetByUserLogin mocks base method.
func (m *MockAlertContactRepository) GetByUserLogin(ctx context.Context, userLogin string) ([]alert.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserLogin", ctx, userLogin)
	ret0, _ := ret[0].([]alert.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserLogin indicates an expected call of GetByUserLogin.
func (mr *MockAlertContactRepositoryMockRecorder) GetByUserLogin(ctx, userLogin interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserLogin", reflect.TypeOf((*MockAlertContactRepository)(nil).GetByUserLogin), ctx, userLogin)
}

// Update mocks base method.
func (m *MockAlertContactRepository) Update(ctx context.Context, contact *alert.Contact) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, contact)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAlertContactRepositoryMockRecorder) Update(ctx, contact interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAlertContactRepository)(nil).Update), ctx, contact)
}
