// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/testmocks/sources/healthcheck_prober_source.go

// Package testmocks is a generated GoMock package.
package testmocks

import (
	probe "WatchTower/internal/domain/entity/probe"
	target "WatchTower/internal/domain/entity/target"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockProber is a mock of Prober interface.
type MockProber struct {
	ctrl     *gomock.Controller
	recorder *MockProberMockRecorder
}

// MockProberMockRecorder is the mock recorder for MockProber.
type MockProberMockRecorder struct {
	mock *MockProber
}

// NewMockProber creates a new mock instance.
func NewMockProber(ctrl *gomock.Controller) *MockProber {
	mock := &MockProber{ctrl: ctrl}
	mock.recorder = &MockProberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProber) EXPECT() *MockProberMockRecorder {
	return m.recorder
}

// Probe mocks base method.
func (m *MockProber) Probe(ctx context.Context, target *target.Target) (probe.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Probe", ctx, target)
	ret0, _ := ret[0].(probe.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Probe indicates an expected call of Probe.
func (mr *MockProberMockRecorder) Probe(ctx, target interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Probe", reflect.TypeOf((*MockProber)(nil).Probe), ctx, target)
}
