// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repo/maintenance_window.go

// Package testmocks is a generated GoMock package.
package testmocks

import (
	maintenance "WatchTower/internal/domain/entity/maintenance"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockMaintenanceWindowRepository is a mock of MaintenanceWindowRepository interface.
type MockMaintenanceWindowRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMaintenanceWindowRepositoryMockRecorder
}

// MockMaintenanceWindowRepositoryMockRecorder is the mock recorder for MockMaintenanceWindowRepository.
type MockMaintenanceWindowRepositoryMockRecorder struct {
	mock *MockMaintenanceWindowRepository
}

// NewMockMaintenanceWindowRepository creates a new mock instance.
func NewMockMaintenanceWindowRepository(ctrl *gomock.Controller) *MockMaintenanceWindowRepository {
	mock := &MockMaintenanceWindowRepository{ctrl: ctrl}
	mock.recorder = &MockMaintenanceWindowRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMaintenanceWindowRepository) EXPECT() *MockMaintenanceWindowRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMaintenanceWindowRepository) Create(ctx context.Context, mw *maintenance.MaintenanceWindow) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, mw)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMaintenanceWindowRepositoryMockRecorder) Create(ctx, mw interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMaintenanceWindowRepository)(nil).Create), ctx, mw)
}

// DeleteByID mocks base method.
func (m *MockMaintenanceWindowRepository) DeleteByID(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockMaintenanceWindowRepositoryMockRecorder) DeleteByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockMaintenanceWindowRepository)(nil).DeleteByID), ctx, id)
}

// GetByID mocks base method.
func (m *MockMaintenanceWindowRepository) GetByID(ctx context.Context, id uuid.UUID) (*maintenance.MaintenanceWindow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*maintenance.MaintenanceWindow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMaintenanceWindowRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMaintenanceWindowRepository)(nil).GetByID), ctx, id)
}

// GetByIDBulk mocks base method.
func (m *MockMaintenanceWindowRepository) GetByIDBulk(ctx context.Context, ids []uuid.UUID) ([]maintenance.MaintenanceWindow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDBulk", ctx, ids)
	ret0, _ := ret[0].([]maintenance.MaintenanceWindow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDBulk indicates an expected call of GetByIDBulk.
func (mr *MockMaintenanceWindowRepositoryMockRecorder) GetByIDBulk(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDBulk", reflect.TypeOf((*MockMaintenanceWindowRepository)(nil).GetByIDBulk), ctx, ids)
}

// GetByUserLogin mocks base method.
func (m *MockMaintenanceWindowRepository) GetByUserLogin(ctx context.Context, userLogin string) ([]maintenance.MaintenanceWindow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserLogin", ctx, userLogin)
	ret0, _ := ret[0].([]maintenance.MaintenanceWindow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserLogin indicates an expected call of GetByUserLogin.
func (mr *MockMaintenanceWindowRepositoryMockRecorder) GetByUserLogin(ctx, userLogin interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserLogin", reflect.TypeOf((*MockMaintenanceWindowRepository)(nil).GetByUserLogin), ctx, userLogin)
}

// LinkMonitor mocks base method.
func (m *MockMaintenanceWindowRepository) LinkMonitor(ctx context.Context, window *maintenance.MaintenanceWindow, monitorID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkMonitor", ctx, window, monitorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkMonitor indicates an expected call of LinkMonitor.
func (mr *MockMaintenanceWindowRepositoryMockRecorder) LinkMonitor(ctx, window, monitorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkMonitor", reflect.TypeOf((*MockMaintenanceWindowRepository)(nil).LinkMonitor), ctx, window, monitorID)
}

// UnlinkMonitor mocks base method.
func (m *MockMaintenanceWindowRepository) UnlinkMonitor(ctx context.Context, window *maintenance.MaintenanceWindow, monitorID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlinkMonitor", ctx, window, monitorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlinkMonitor indicates an expected call of UnlinkMonitor.
func (mr *MockMaintenanceWindowRepositoryMockRecorder) UnlinkMonitor(ctx, window, monitorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkMonitor", reflect.TypeOf((*MockMaintenanceWindowRepository)(nil).UnlinkMonitor), ctx, window, monitorID)
}

// Update mocks base method.
func (m *MockMaintenanceWindowRepository) Update(ctx context.Context, mw *maintenance.MaintenanceWindow) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, mw)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMaintenanceWindowRepositoryMockRecorder) Update(ctx, mw interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMaintenanceWindowRepository)(nil).Update), ctx, mw)
}
