// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repo/monitor.go

// Package testmocks is a generated GoMock package.
package testmocks

import (
	alert "WatchTower/internal/domain/entity/alert_contact"
	monitor "WatchTower/internal/domain/entity/monitor"
	user "WatchTower/internal/domain/entity/user"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockMonitorRepository is a mock of MonitorRepository interface.
type MockMonitorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMonitorRepositoryMockRecorder
}

// MockMonitorRepositoryMockRecorder is the mock recorder for MockMonitorRepository.
type MockMonitorRepositoryMockRecorder struct {
	mock *MockMonitorRepository
}

// NewMockMonitorRepository creates a new mock instance.
func NewMockMonitorRepository(ctrl *gomock.Controller) *MockMonitorRepository {
	mock := &MockMonitorRepository{ctrl: ctrl}
	mock.recorder = &MockMonitorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMonitorRepository) EXPECT() *MockMonitorRepositoryMockRecorder {
	return m.recorder
}

// AddAlertContact mocks base method.
func (m *MockMonitorRepository) AddAlertContact(ctx context.Context, mon *monitor.Monitor, contact *alert.Contact) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAlertContact", ctx, mon, contact)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAlertContact indicates an expected call of AddAlertContact.
func (mr *MockMonitorRepositoryMockRecorder) AddAlertContact(ctx, mon, contact interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAlertContact", reflect.TypeOf((*MockMonitorRepository)(nil).AddAlertContact), ctx, mon, contact)
}

// BulkUpdateEvaluation mocks base method.
func (m *MockMonitorRepository) BulkUpdateEvaluation(ctx context.Context, monitors []*monitor.Monitor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdateEvaluation", ctx, monitors)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkUpdateEvaluation indicates an expected call of BulkUpdateEvaluation.
func (mr *MockMonitorRepositoryMockRecorder) BulkUpdateEvaluation(ctx, monitors interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdateEvaluation", reflect.TypeOf((*MockMonitorRepository)(nil).BulkUpdateEvaluation), ctx, monitors)
}

// Create mocks base method.
func (m *MockMonitorRepository) Create(ctx context.Context, mon *monitor.Monitor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, mon)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMonitorRepositoryMockRecorder) Create(ctx, mon interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMonitorRepository)(nil).Create), ctx, mon)
}

// DeleteByID mocks base method.
func (m *MockMonitorRepository) DeleteByID(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockMonitorRepositoryMockRecorder) DeleteByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockMonitorRepository)(nil).DeleteByID), ctx, id)
}

// Disable mocks base method.
func (m *MockMonitorRepository) Disable(ctx context.Context, monitorID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disable", ctx, monitorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Disable indicates an expected call of Disable.
func (mr *MockMonitorRepositoryMockRecorder) Disable(ctx, monitorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disable", reflect.TypeOf((*MockMonitorRepository)(nil).Disable), ctx, monitorID)
}

// Enable mocks base method.
func (m *MockMonitorRepository) Enable(ctx context.Context, monitorID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enable", ctx, monitorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enable indicates an expected call of Enable.
func (mr *MockMonitorRepositoryMockRecorder) Enable(ctx, monitorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enable", reflect.TypeOf((*MockMonitorRepository)(nil).Enable), ctx, monitorID)
}

// GetAllByTargetID mocks base method.
func (m *MockMonitorRepository) GetAllByTargetID(ctx context.Context, targetID uuid.UUID) ([]*monitor.Monitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllByTargetID", ctx, targetID)
	ret0, _ := ret[0].([]*monitor.Monitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllByTargetID indicates an expected call of GetAllByTargetID.
func (mr *MockMonitorRepositoryMockRecorder) GetAllByTargetID(ctx, targetID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllByTargetID", reflect.TypeOf((*MockMonitorRepository)(nil).GetAllByTargetID), ctx, targetID)
}

// GetAllByUser mocks base method.
func (m *MockMonitorRepository) GetAllByUser(ctx context.Context, usr *user.User) ([]*monitor.Monitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllByUser", ctx, usr)
	ret0, _ := ret[0].([]*monitor.Monitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllByUser indicates an expected call of GetAllByUser.
func (mr *MockMonitorRepositoryMockRecorder) GetAllByUser(ctx, usr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllByUser", reflect.TypeOf((*MockMonitorRepository)(nil).GetAllByUser), ctx, usr)
}

// GetByID mocks base method.
func (m *MockMonitorRepository) GetByID(ctx context.Context, id uuid.UUID) (*monitor.Monitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*monitor.Monitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMonitorRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMonitorRepository)(nil).GetByID), ctx, id)
}

// GetMonitorsToEvaluate mocks base method.
func (m *MockMonitorRepository) GetMonitorsToEvaluate(ctx context.Context, targetIDs []uuid.UUID) (map[uuid.UUID]*monitor.Monitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMonitorsToEvaluate", ctx, targetIDs)
	ret0, _ := ret[0].(map[uuid.UUID]*monitor.Monitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMonitorsToEvaluate indicates an expected call of GetMonitorsToEvaluate.
func (mr *MockMonitorRepositoryMockRecorder) GetMonitorsToEvaluate(ctx, targetIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMonitorsToEvaluate", reflect.TypeOf((*MockMonitorRepository)(nil).GetMonitorsToEvaluate), ctx, targetIDs)
}

// RemoveAlertContact mocks base method.
func (m *MockMonitorRepository) RemoveAlertContact(ctx context.Context, mon *monitor.Monitor, contact *alert.Contact) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAlertContact", ctx, mon, contact)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAlertContact indicates an expected call of RemoveAlertContact.
func (mr *MockMonitorRepositoryMockRecorder) RemoveAlertContact(ctx, mon, contact interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAlertContact", reflect.TypeOf((*MockMonitorRepository)(nil).RemoveAlertContact), ctx, mon, contact)
}

// Update mocks base method.
func (m *MockMonitorRepository) Update(ctx context.Context, mon *monitor.Monitor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, mon)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMonitorRepositoryMockRecorder) Update(ctx, mon interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMonitorRepository)(nil).Update), ctx, mon)
}
