// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repo/probe_summary.go

// Package testmocks is a generated GoMock package.
package testmocks

import (
	probe "WatchTower/internal/domain/entity/probe"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockProbeSummaryRepository is a mock of ProbeSummaryRepository interface.
type MockProbeSummaryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProbeSummaryRepositoryMockRecorder
}

// MockProbeSummaryRepositoryMockRecorder is the mock recorder for MockProbeSummaryRepository.
type MockProbeSummaryRepositoryMockRecorder struct {
	mock *MockProbeSummaryRepository
}

// NewMockProbeSummaryRepository creates a new mock instance.
func NewMockProbeSummaryRepository(ctrl *gomock.Controller) *MockProbeSummaryRepository {
	mock := &MockProbeSummaryRepository{ctrl: ctrl}
	mock.recorder = &MockProbeSummaryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProbeSummaryRepository) EXPECT() *MockProbeSummaryRepositoryMockRecorder {
	return m.recorder
}

// BulkCreate mocks base method.
func (m *MockProbeSummaryRepository) BulkCreate(ctx context.Context, summaries []*probe.Summary) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCreate", ctx, summaries)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkCreate indicates an expected call of BulkCreate.
func (mr *MockProbeSummaryRepositoryMockRecorder) BulkCreate(ctx, summaries interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCreate", reflect.TypeOf((*MockProbeSummaryRepository)(nil).BulkCreate), ctx, summaries)
}

// Create mocks base method.
func (m *MockProbeSummaryRepository) Create(ctx context.Context, summary *probe.Summary) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, summary)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProbeSummaryRepositoryMockRecorder) Create(ctx, summary interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProbeSummaryRepository)(nil).Create), ctx, summary)
}

// GetByMonitorID mocks base method.
func (m *MockProbeSummaryRepository) GetByMonitorID(ctx context.Context, monitorID uuid.UUID, limit int) ([]*probe.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByMonitorID", ctx, monitorID, limit)
	ret0, _ := ret[0].([]*probe.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByMonitorID indicates an expected call of GetByMonitorID.
func (mr *MockProbeSummaryRepositoryMockRecorder) GetByMonitorID(ctx, monitorID, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByMonitorID", reflect.TypeOf((*MockProbeSummaryRepository)(nil).GetByMonitorID), ctx, monitorID, limit)
}
