// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/testmocks/sources/probe_evaluator_source.go

// Package testmocks is a generated GoMock package.
package testmocks

import (
	monitor "WatchTower/internal/domain/entity/monitor"
	probe "WatchTower/internal/domain/entity/probe"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockProbeEvaluator is a mock of ProbeEvaluator interface.
type MockProbeEvaluator struct {
	ctrl     *gomock.Controller
	recorder *MockProbeEvaluatorMockRecorder
}

// MockProbeEvaluatorMockRecorder is the mock recorder for MockProbeEvaluator.
type MockProbeEvaluatorMockRecorder struct {
	mock *MockProbeEvaluator
}

// NewMockProbeEvaluator creates a new mock instance.
func NewMockProbeEvaluator(ctrl *gomock.Controller) *MockProbeEvaluator {
	mock := &MockProbeEvaluator{ctrl: ctrl}
	mock.recorder = &MockProbeEvaluatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProbeEvaluator) EXPECT() *MockProbeEvaluatorMockRecorder {
	return m.recorder
}

// Evaluate mocks base method.
func (m *MockProbeEvaluator) Evaluate(ctx context.Context, probeResult *probe.Result, mon *monitor.Monitor) (monitor.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evaluate", ctx, probeResult, mon)
	ret0, _ := ret[0].(monitor.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Evaluate indicates an expected call of Evaluate.
func (mr *MockProbeEvaluatorMockRecorder) Evaluate(ctx, probeResult, mon interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evaluate", reflect.TypeOf((*MockProbeEvaluator)(nil).Evaluate), ctx, probeResult, mon)
}
