// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repo/target.go

// Package testmocks is a generated GoMock package.
package testmocks

import (
	target "WatchTower/internal/domain/entity/target"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockTargetRepository is a mock of TargetRepository interface.
type MockTargetRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTargetRepositoryMockRecorder
}

// MockTargetRepositoryMockRecorder is the mock recorder for MockTargetRepository.
type MockTargetRepositoryMockRecorder struct {
	mock *MockTargetRepository
}

// NewMockTargetRepository creates a new mock instance.
func NewMockTargetRepository(ctrl *gomock.Controller) *MockTargetRepository {
	mock := &MockTargetRepository{ctrl: ctrl}
	mock.recorder = &MockTargetRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTargetRepository) EXPECT() *MockTargetRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTargetRepository) Create(ctx context.Context, tgt *target.Target) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tgt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTargetRepositoryMockRecorder) Create(ctx, tgt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTargetRepository)(nil).Create), ctx, tgt)
}

// DeleteByID mocks base method.
func (m *MockTargetRepository) DeleteByID(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockTargetRepositoryMockRecorder) DeleteByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockTargetRepository)(nil).DeleteByID), ctx, id)
}

// Disable mocks base method.
func (m *MockTargetRepository) Disable(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disable", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Disable indicates an expected call of Disable.
func (mr *MockTargetRepositoryMockRecorder) Disable(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disable", reflect.TypeOf((*MockTargetRepository)(nil).Disable), ctx, id)
}

// Enable mocks base method.
func (m *MockTargetRepository) Enable(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enable", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enable indicates an expected call of Enable.
func (mr *MockTargetRepositoryMockRecorder) Enable(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enable", reflect.TypeOf((*MockTargetRepository)(nil).Enable), ctx, id)
}

// GetAllActive mocks base method.
func (m *MockTargetRepository) GetAllActive(ctx context.Context) ([]target.Target, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllActive", ctx)
	ret0, _ := ret[0].([]target.Target)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllActive indicates an expected call of GetAllActive.
func (mr *MockTargetRepositoryMockRecorder) GetAllActive(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllActive", reflect.TypeOf((*MockTargetRepository)(nil).GetAllActive), ctx)
}

// GetByHash mocks base method.
func (m *MockTargetRepository) GetByHash(ctx context.Context, hash string) (*target.Target, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHash", ctx, hash)
	ret0, _ := ret[0].(*target.Target)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByHash indicates an expected call of GetByHash.
func (mr *MockTargetRepositoryMockRecorder) GetByHash(ctx, hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHash", reflect.TypeOf((*MockTargetRepository)(nil).GetByHash), ctx, hash)
}

// GetByID mocks base method.
func (m *MockTargetRepository) GetByID(ctx context.Context, id uuid.UUID) (*target.Target, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*target.Target)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTargetRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTargetRepository)(nil).GetByID), ctx, id)
}

// Update mocks base method.
func (m *MockTargetRepository) Update(ctx context.Context, tgt *target.Target) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tgt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTargetRepositoryMockRecorder) Update(ctx, tgt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTargetRepository)(nil).Update), ctx, tgt)
}

// UpdateProbeInterval mocks base method.
func (m *MockTargetRepository) UpdateProbeInterval(ctx context.Context, id uuid.UUID, probeIntervalSec int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProbeInterval", ctx, id, probeIntervalSec)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProbeInterval indicates an expected call of UpdateProbeInterval.
func (mr *MockTargetRepositoryMockRecorder) UpdateProbeInterval(ctx, id, probeIntervalSec interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProbeInterval", reflect.TypeOf((*MockTargetRepository)(nil).UpdateProbeInterval), ctx, id, probeIntervalSec)
}
