// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alert_contact.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAlertContact = `-- name: CreateAlertContact :exec

INSERT INTO "alert_contact" (id, user_login, type, label, config, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAlertContactParams struct {
	ID        pgtype.UUID `json:"id"`
	UserLogin string      `json:"user_login"`
	Type      ContactType `json:"type"`
	Label     string      `json:"label"`
	Config    []byte      `json:"config"`
	IsActive  bool        `json:"is_active"`
}

// // GetByIDBulk retrieves multiple alert contacts by their IDs. Returns a slice of found contacts.
// GetByIDBulk(ctx context.Context, ids []uuid.UUID) ([]alert.Contact, error)
func (q *Queries) CreateAlertContact(ctx context.Context, arg CreateAlertContactParams) error {
	_, err := q.db.Exec(ctx, createAlertContact,
		arg.ID,
		arg.UserLogin,
		arg.Type,
		arg.Label,
		arg.Config,
		arg.IsActive,
	)
	return err
}

const deleteAlertContactByID = `-- name: DeleteAlertContactByID :exec
DELETE
FROM "alert_contact"
WHERE id = $1
`

func (q *Queries) DeleteAlertContactByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAlertContactByID, id)
	return err
}

const disableAlertContact = `-- name: DisableAlertContact :exec
UPDATE "alert_contact"
SET is_active = FALSE
WHERE id = $1
  AND is_active = TRUE
`

func (q *Queries) DisableAlertContact(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, disableAlertContact, id)
	return err
}

const enableAlertContact = `-- name: EnableAlertContact :exec
UPDATE "alert_contact"
SET is_active = TRUE
WHERE id = $1
  AND is_active = FALSE
`

func (q *Queries) EnableAlertContact(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, enableAlertContact, id)
	return err
}

const getAlertContactByID = `-- name: GetAlertContactByID :one
SELECT a.id, a.user_login, a.type, a.label, a.config, a.is_active, u.login, u.password_hash
FROM "alert_contact" a
         JOIN "user" u ON a.user_login = u.login
WHERE id = $1
`

type GetAlertContactByIDRow struct {
	ID           pgtype.UUID `json:"id"`
	UserLogin    string      `json:"user_login"`
	Type         ContactType `json:"type"`
	Label        string      `json:"label"`
	Config       []byte      `json:"config"`
	IsActive     bool        `json:"is_active"`
	Login        string      `json:"login"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) GetAlertContactByID(ctx context.Context, id pgtype.UUID) (GetAlertContactByIDRow, error) {
	row := q.db.QueryRow(ctx, getAlertContactByID, id)
	var i GetAlertContactByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserLogin,
		&i.Type,
		&i.Label,
		&i.Config,
		&i.IsActive,
		&i.Login,
		&i.PasswordHash,
	)
	return i, err
}

const getAlertContactsByIDBulk = `-- name: GetAlertContactsByIDBulk :many
SELECT a.id, a.user_login, a.type, a.label, a.config, a.is_active, u.login, u.password_hash
FROM "alert_contact" a
         JOIN "user" u ON a.user_login = u.login
WHERE a.id = ANY ($1::uuid[])
`

type GetAlertContactsByIDBulkRow struct {
	ID           pgtype.UUID `json:"id"`
	UserLogin    string      `json:"user_login"`
	Type         ContactType `json:"type"`
	Label        string      `json:"label"`
	Config       []byte      `json:"config"`
	IsActive     bool        `json:"is_active"`
	Login        string      `json:"login"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) GetAlertContactsByIDBulk(ctx context.Context, ids []pgtype.UUID) ([]GetAlertContactsByIDBulkRow, error) {
	rows, err := q.db.Query(ctx, getAlertContactsByIDBulk, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAlertContactsByIDBulkRow
	for rows.Next() {
		var i GetAlertContactsByIDBulkRow
		if err := rows.Scan(
			&i.ID,
			&i.UserLogin,
			&i.Type,
			&i.Label,
			&i.Config,
			&i.IsActive,
			&i.Login,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlertContactsByUserLogin = `-- name: GetAlertContactsByUserLogin :many
SELECT a.id, a.user_login, a.type, a.label, a.config, a.is_active, u.login, u.password_hash
FROM "alert_contact" a
         JOIN "user" u ON a.user_login = u.login
WHERE a.user_login = $1
`

type GetAlertContactsByUserLoginRow struct {
	ID           pgtype.UUID `json:"id"`
	UserLogin    string      `json:"user_login"`
	Type         ContactType `json:"type"`
	Label        string      `json:"label"`
	Config       []byte      `json:"config"`
	IsActive     bool        `json:"is_active"`
	Login        string      `json:"login"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) GetAlertContactsByUserLogin(ctx context.Context, userLogin string) ([]GetAlertContactsByUserLoginRow, error) {
	rows, err := q.db.Query(ctx, getAlertContactsByUserLogin, userLogin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAlertContactsByUserLoginRow
	for rows.Next() {
		var i GetAlertContactsByUserLoginRow
		if err := rows.Scan(
			&i.ID,
			&i.UserLogin,
			&i.Type,
			&i.Label,
			&i.Config,
			&i.IsActive,
			&i.Login,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlertContact = `-- name: UpdateAlertContact :exec
UPDATE "alert_contact"
SET user_login = $2,
    type       = $3,
    label      = $4,
    config     = $5
WHERE id = $1
`

type UpdateAlertContactParams struct {
	ID        pgtype.UUID `json:"id"`
	UserLogin string      `json:"user_login"`
	Type      ContactType `json:"type"`
	Label     string      `json:"label"`
	Config    []byte      `json:"config"`
}

func (q *Queries) UpdateAlertContact(ctx context.Context, arg UpdateAlertContactParams) error {
	_, err := q.db.Exec(ctx, updateAlertContact,
		arg.ID,
		arg.UserLogin,
		arg.Type,
		arg.Label,
		arg.Config,
	)
	return err
}
