// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: maintenance_window.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMaintenanceWindow = `-- name: CreateMaintenanceWindow :exec
INSERT INTO "maintenance_window" (id, user_login, title, description, type, config)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateMaintenanceWindowParams struct {
	ID          pgtype.UUID     `json:"id"`
	UserLogin   string          `json:"user_login"`
	Title       string          `json:"title"`
	Description pgtype.Text     `json:"description"`
	Type        MaintenanceType `json:"type"`
	Config      []byte          `json:"config"`
}

func (q *Queries) CreateMaintenanceWindow(ctx context.Context, arg CreateMaintenanceWindowParams) error {
	_, err := q.db.Exec(ctx, createMaintenanceWindow,
		arg.ID,
		arg.UserLogin,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.Config,
	)
	return err
}

const deleteMaintenanceWindowByID = `-- name: DeleteMaintenanceWindowByID :exec
DELETE
FROM "maintenance_window"
WHERE id = $1
`

func (q *Queries) DeleteMaintenanceWindowByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMaintenanceWindowByID, id)
	return err
}

const geMaintenanceWindowsByIDBulk = `-- name: GeMaintenanceWindowsByIDBulk :many
SELECT m.id, m.user_login, m.title, m.description, m.type, m.config, u.login, u.password_hash
FROM "maintenance_window" m
         JOIN "user" u ON m.user_login = u.login
WHERE m.id = ANY ($1::uuid[])
`

type GeMaintenanceWindowsByIDBulkRow struct {
	MaintenanceWindow MaintenanceWindow `json:"maintenance_window"`
	User              User              `json:"user"`
}

func (q *Queries) GeMaintenanceWindowsByIDBulk(ctx context.Context, ids []pgtype.UUID) ([]GeMaintenanceWindowsByIDBulkRow, error) {
	rows, err := q.db.Query(ctx, geMaintenanceWindowsByIDBulk, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GeMaintenanceWindowsByIDBulkRow
	for rows.Next() {
		var i GeMaintenanceWindowsByIDBulkRow
		if err := rows.Scan(
			&i.MaintenanceWindow.ID,
			&i.MaintenanceWindow.UserLogin,
			&i.MaintenanceWindow.Title,
			&i.MaintenanceWindow.Description,
			&i.MaintenanceWindow.Type,
			&i.MaintenanceWindow.Config,
			&i.User.Login,
			&i.User.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaintenanceWindowByID = `-- name: GetMaintenanceWindowByID :one
SELECT m.id, m.user_login, m.title, m.description, m.type, m.config, u.login, u.password_hash
FROM "maintenance_window" m
         JOIN "user" u ON m.user_login = u.login
WHERE id = $1
`

type GetMaintenanceWindowByIDRow struct {
	MaintenanceWindow MaintenanceWindow `json:"maintenance_window"`
	User              User              `json:"user"`
}

func (q *Queries) GetMaintenanceWindowByID(ctx context.Context, id pgtype.UUID) (GetMaintenanceWindowByIDRow, error) {
	row := q.db.QueryRow(ctx, getMaintenanceWindowByID, id)
	var i GetMaintenanceWindowByIDRow
	err := row.Scan(
		&i.MaintenanceWindow.ID,
		&i.MaintenanceWindow.UserLogin,
		&i.MaintenanceWindow.Title,
		&i.MaintenanceWindow.Description,
		&i.MaintenanceWindow.Type,
		&i.MaintenanceWindow.Config,
		&i.User.Login,
		&i.User.PasswordHash,
	)
	return i, err
}

const getMaintenanceWindowsByUserLogin = `-- name: GetMaintenanceWindowsByUserLogin :many
SELECT m.id, m.user_login, m.title, m.description, m.type, m.config, u.login, u.password_hash
FROM "maintenance_window" m
         JOIN "user" u ON m.user_login = u.login
WHERE m.user_login = $1
ORDER BY m.title
`

type GetMaintenanceWindowsByUserLoginRow struct {
	MaintenanceWindow MaintenanceWindow `json:"maintenance_window"`
	User              User              `json:"user"`
}

func (q *Queries) GetMaintenanceWindowsByUserLogin(ctx context.Context, userLogin string) ([]GetMaintenanceWindowsByUserLoginRow, error) {
	rows, err := q.db.Query(ctx, getMaintenanceWindowsByUserLogin, userLogin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMaintenanceWindowsByUserLoginRow
	for rows.Next() {
		var i GetMaintenanceWindowsByUserLoginRow
		if err := rows.Scan(
			&i.MaintenanceWindow.ID,
			&i.MaintenanceWindow.UserLogin,
			&i.MaintenanceWindow.Title,
			&i.MaintenanceWindow.Description,
			&i.MaintenanceWindow.Type,
			&i.MaintenanceWindow.Config,
			&i.User.Login,
			&i.User.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkMonitor = `-- name: LinkMonitor :exec
INSERT INTO "maintenance_window_monitor" (monitor_id, window_id)
VALUES ($1, $2)
`

type LinkMonitorParams struct {
	MonitorID pgtype.UUID `json:"monitor_id"`
	WindowID  pgtype.UUID `json:"window_id"`
}

func (q *Queries) LinkMonitor(ctx context.Context, arg LinkMonitorParams) error {
	_, err := q.db.Exec(ctx, linkMonitor, arg.MonitorID, arg.WindowID)
	return err
}

const unlinkMonitor = `-- name: UnlinkMonitor :exec
DELETE
FROM "maintenance_window_monitor"
WHERE monitor_id = $1
  AND window_id = $2
`

type UnlinkMonitorParams struct {
	MonitorID pgtype.UUID `json:"monitor_id"`
	WindowID  pgtype.UUID `json:"window_id"`
}

func (q *Queries) UnlinkMonitor(ctx context.Context, arg UnlinkMonitorParams) error {
	_, err := q.db.Exec(ctx, unlinkMonitor, arg.MonitorID, arg.WindowID)
	return err
}

const updateMaintenanceWindow = `-- name: UpdateMaintenanceWindow :exec
UPDATE "maintenance_window"
SET user_login  = $2,
    title       = $3,
    description = $4,
    type        = $5,
    config      = $6
WHERE id = $1
`

type UpdateMaintenanceWindowParams struct {
	ID          pgtype.UUID     `json:"id"`
	UserLogin   string          `json:"user_login"`
	Title       string          `json:"title"`
	Description pgtype.Text     `json:"description"`
	Type        MaintenanceType `json:"type"`
	Config      []byte          `json:"config"`
}

func (q *Queries) UpdateMaintenanceWindow(ctx context.Context, arg UpdateMaintenanceWindowParams) error {
	_, err := q.db.Exec(ctx, updateMaintenanceWindow,
		arg.ID,
		arg.UserLogin,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.Config,
	)
	return err
}
