// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSLAStat = `-- name: GetSLAStat :one
with bounds as (
    select
        $1::uuid as monitor_id,
        $2::timestamp as period_start,
        $3::timestamp as period_end
), clipped as (
    select
        b.monitor_id,
        greatest(msl.start_time, b.period_start) as interval_start,
        least(msl.end_time, b.period_end) as interval_end,
        msl.status
    from bounds b
             left join monitor_status_log msl
                       on msl.monitor_id = b.monitor_id
                           and msl.end_time > b.period_start
                           and msl.start_time < b.period_end
), totals as (
    select
        c.monitor_id,
        coalesce(sum(
                         case
                             when c.status = 'UP' and c.interval_end > c.interval_start
                                 then extract(epoch from (c.interval_end - c.interval_start))
                             else 0
                             end
                 ), 0)::double precision as uptime_sec,
        coalesce(sum(
                         case
                             when c.status is not null
                                 and c.status <> 'UP'
                                 and c.interval_end > c.interval_start
                                 then extract(epoch from (c.interval_end - c.interval_start))
                             else 0
                             end
                 ), 0)::double precision as downtime_sec
    from clipped c
    group by c.monitor_id
)
select
    b.monitor_id,
    case
        when b.period_end <= b.period_start then 0::double precision
        else (t.uptime_sec * 100.0) / extract(epoch from (b.period_end - b.period_start))
        end as uptime_percent,
    t.downtime_sec::int as total_downtime_sec,
    b.period_start,
    b.period_end
from bounds b
         join totals t on t.monitor_id = b.monitor_id
`

type GetSLAStatParams struct {
	Column1 pgtype.UUID      `json:"column_1"`
	Column2 pgtype.Timestamp `json:"column_2"`
	Column3 pgtype.Timestamp `json:"column_3"`
}

type GetSLAStatRow struct {
	MonitorID        pgtype.UUID      `json:"monitor_id"`
	UptimePercent    interface{}      `json:"uptime_percent"`
	TotalDowntimeSec int32            `json:"total_downtime_sec"`
	PeriodStart      pgtype.Timestamp `json:"period_start"`
	PeriodEnd        pgtype.Timestamp `json:"period_end"`
}

func (q *Queries) GetSLAStat(ctx context.Context, arg GetSLAStatParams) (GetSLAStatRow, error) {
	row := q.db.QueryRow(ctx, getSLAStat, arg.Column1, arg.Column2, arg.Column3)
	var i GetSLAStatRow
	err := row.Scan(
		&i.MonitorID,
		&i.UptimePercent,
		&i.TotalDowntimeSec,
		&i.PeriodStart,
		&i.PeriodEnd,
	)
	return i, err
}

const getStatusHistory = `-- name: GetStatusHistory :many
select msl.id, msl.monitor_id, msl.status, msl.start_time, msl.end_time
from monitor_status_log msl
where msl.monitor_id = $1
  and msl.end_time > $2
  and msl.start_time <= $3
order by msl.start_time desc
`

type GetStatusHistoryParams struct {
	MonitorID pgtype.UUID      `json:"monitor_id"`
	EndTime   pgtype.Timestamp `json:"end_time"`
	StartTime pgtype.Timestamp `json:"start_time"`
}

func (q *Queries) GetStatusHistory(ctx context.Context, arg GetStatusHistoryParams) ([]MonitorStatusLog, error) {
	rows, err := q.db.Query(ctx, getStatusHistory, arg.MonitorID, arg.EndTime, arg.StartTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonitorStatusLog
	for rows.Next() {
		var i MonitorStatusLog
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.Status,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
