// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ContactType string

const (
	ContactTypeTELEGRAM ContactType = "TELEGRAM"
)

func (e *ContactType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContactType(s)
	case string:
		*e = ContactType(s)
	default:
		return fmt.Errorf("unsupported scan type for ContactType: %T", src)
	}
	return nil
}

type NullContactType struct {
	ContactType ContactType `json:"contact_type"`
	Valid       bool        `json:"valid"` // Valid is true if ContactType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContactType) Scan(value interface{}) error {
	if value == nil {
		ns.ContactType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContactType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContactType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContactType), nil
}

type MaintenanceType string

const (
	MaintenanceTypeONCE   MaintenanceType = "ONCE"
	MaintenanceTypeMANUAL MaintenanceType = "MANUAL"
)

func (e *MaintenanceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MaintenanceType(s)
	case string:
		*e = MaintenanceType(s)
	default:
		return fmt.Errorf("unsupported scan type for MaintenanceType: %T", src)
	}
	return nil
}

type NullMaintenanceType struct {
	MaintenanceType MaintenanceType `json:"maintenance_type"`
	Valid           bool            `json:"valid"` // Valid is true if MaintenanceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMaintenanceType) Scan(value interface{}) error {
	if value == nil {
		ns.MaintenanceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MaintenanceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMaintenanceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MaintenanceType), nil
}

type ProcessingStatusType string

const (
	ProcessingStatusTypeNEW       ProcessingStatusType = "NEW"
	ProcessingStatusTypePROCESSED ProcessingStatusType = "PROCESSED"
	ProcessingStatusTypeCANCELLED ProcessingStatusType = "CANCELLED"
)

func (e *ProcessingStatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProcessingStatusType(s)
	case string:
		*e = ProcessingStatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for ProcessingStatusType: %T", src)
	}
	return nil
}

type NullProcessingStatusType struct {
	ProcessingStatusType ProcessingStatusType `json:"processing_status_type"`
	Valid                bool                 `json:"valid"` // Valid is true if ProcessingStatusType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProcessingStatusType) Scan(value interface{}) error {
	if value == nil {
		ns.ProcessingStatusType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProcessingStatusType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProcessingStatusType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProcessingStatusType), nil
}

type ProtocolType string

const (
	ProtocolTypeHTTP ProtocolType = "HTTP"
	ProtocolTypeTCP  ProtocolType = "TCP"
	ProtocolTypeICMP ProtocolType = "ICMP"
)

func (e *ProtocolType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProtocolType(s)
	case string:
		*e = ProtocolType(s)
	default:
		return fmt.Errorf("unsupported scan type for ProtocolType: %T", src)
	}
	return nil
}

type NullProtocolType struct {
	ProtocolType ProtocolType `json:"protocol_type"`
	Valid        bool         `json:"valid"` // Valid is true if ProtocolType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProtocolType) Scan(value interface{}) error {
	if value == nil {
		ns.ProtocolType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProtocolType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProtocolType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProtocolType), nil
}

type StatusType string

const (
	StatusTypeUP          StatusType = "UP"
	StatusTypeDOWN        StatusType = "DOWN"
	StatusTypeMAINTENANCE StatusType = "MAINTENANCE"
	StatusTypeUNKNOWN     StatusType = "UNKNOWN"
)

func (e *StatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatusType(s)
	case string:
		*e = StatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for StatusType: %T", src)
	}
	return nil
}

type NullStatusType struct {
	StatusType StatusType `json:"status_type"`
	Valid      bool       `json:"valid"` // Valid is true if StatusType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatusType) Scan(value interface{}) error {
	if value == nil {
		ns.StatusType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatusType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatusType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatusType), nil
}

type AlertContact struct {
	ID        pgtype.UUID `json:"id"`
	UserLogin string      `json:"user_login"`
	Type      ContactType `json:"type"`
	Label     string      `json:"label"`
	Config    []byte      `json:"config"`
	IsActive  bool        `json:"is_active"`
}

type MaintenanceWindow struct {
	ID          pgtype.UUID     `json:"id"`
	UserLogin   string          `json:"user_login"`
	Title       string          `json:"title"`
	Description pgtype.Text     `json:"description"`
	Type        MaintenanceType `json:"type"`
	Config      []byte          `json:"config"`
}

type MaintenanceWindowMonitor struct {
	MonitorID pgtype.UUID `json:"monitor_id"`
	WindowID  pgtype.UUID `json:"window_id"`
}

type Monitor struct {
	ID               pgtype.UUID        `json:"id"`
	TargetID         pgtype.UUID        `json:"target_id"`
	UserLogin        string             `json:"user_login"`
	Label            string             `json:"label"`
	IsActive         bool               `json:"is_active"`
	ProbeIntervalSec int32              `json:"probe_interval_sec"`
	Expectations     []byte             `json:"expectations"`
	CurrentStatus    StatusType         `json:"current_status"`
	LastEvaluatedAt  pgtype.Timestamptz `json:"last_evaluated_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type MonitorAlertContact struct {
	MonitorID pgtype.UUID `json:"monitor_id"`
	ContactID pgtype.UUID `json:"contact_id"`
}

type MonitorStatusLog struct {
	ID        int64              `json:"id"`
	MonitorID pgtype.UUID        `json:"monitor_id"`
	Status    StatusType         `json:"status"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

type ProbeResult struct {
	ID               pgtype.UUID          `json:"id"`
	TargetID         pgtype.UUID          `json:"target_id"`
	ProbeTime        pgtype.Timestamptz   `json:"probe_time"`
	LatencyMs        int32                `json:"latency_ms"`
	StatusCode       pgtype.Int4          `json:"status_code"`
	NetworkFailure   bool                 `json:"network_failure"`
	ErrorMessage     pgtype.Text          `json:"error_message"`
	Meta             []byte               `json:"meta"`
	ProcessingStatus ProcessingStatusType `json:"processing_status"`
}

type Target struct {
	ID               pgtype.UUID  `json:"id"`
	SignatureHash    string       `json:"signature_hash"`
	Protocol         ProtocolType `json:"protocol"`
	IsActive         bool         `json:"is_active"`
	Endpoint         string       `json:"endpoint"`
	NetworkConfig    []byte       `json:"network_config"`
	ProbeIntervalSec int32        `json:"probe_interval_sec"`
}

type User struct {
	Login        string `json:"login"`
	PasswordHash string `json:"password_hash"`
}
