// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitor.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAlertContactToMonitor = `-- name: AddAlertContactToMonitor :exec
INSERT INTO "monitor_alert_contact" (monitor_id, contact_id)
VALUES ($1, $2)
`

type AddAlertContactToMonitorParams struct {
	MonitorID pgtype.UUID `json:"monitor_id"`
	ContactID pgtype.UUID `json:"contact_id"`
}

func (q *Queries) AddAlertContactToMonitor(ctx context.Context, arg AddAlertContactToMonitorParams) error {
	_, err := q.db.Exec(ctx, addAlertContactToMonitor, arg.MonitorID, arg.ContactID)
	return err
}

const bulkUpdateEvaluation = `-- name: BulkUpdateEvaluation :exec
UPDATE "monitor" AS m
SET current_status    = c.current_status,
    last_evaluated_at = c.last_evaluated_at
FROM (
    SELECT unnest($1::uuid[]) AS id,
           unnest($2::text[])::status_type AS current_status,
           unnest($3::TIMESTAMP[]) AS last_evaluated_at
) AS c
WHERE m.id = c.id
  AND m.is_active = TRUE
`

type BulkUpdateEvaluationParams struct {
	Ids          []pgtype.UUID      `json:"ids"`
	Statuses     []string           `json:"statuses"`
	EvaluatedAts []pgtype.Timestamp `json:"evaluated_ats"`
}

func (q *Queries) BulkUpdateEvaluation(ctx context.Context, arg BulkUpdateEvaluationParams) error {
	_, err := q.db.Exec(ctx, bulkUpdateEvaluation, arg.Ids, arg.Statuses, arg.EvaluatedAts)
	return err
}

const createMonitor = `-- name: CreateMonitor :exec
INSERT INTO "monitor" (id, target_id, user_login, label, is_active, probe_interval_sec, expectations, current_status,
                       last_evaluated_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateMonitorParams struct {
	ID               pgtype.UUID      `json:"id"`
	TargetID         pgtype.UUID      `json:"target_id"`
	UserLogin        string           `json:"user_login"`
	Label            string           `json:"label"`
	IsActive         bool             `json:"is_active"`
	ProbeIntervalSec int32            `json:"probe_interval_sec"`
	Expectations     []byte           `json:"expectations"`
	CurrentStatus    StatusType       `json:"current_status"`
	LastEvaluatedAt  pgtype.Timestamp `json:"last_evaluated_at"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) error {
	_, err := q.db.Exec(ctx, createMonitor,
		arg.ID,
		arg.TargetID,
		arg.UserLogin,
		arg.Label,
		arg.IsActive,
		arg.ProbeIntervalSec,
		arg.Expectations,
		arg.CurrentStatus,
		arg.LastEvaluatedAt,
		arg.CreatedAt,
	)
	return err
}

const deleteMonitorByID = `-- name: DeleteMonitorByID :exec
DELETE
FROM "monitor"
WHERE id = $1
`

func (q *Queries) DeleteMonitorByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMonitorByID, id)
	return err
}

const disableMonitor = `-- name: DisableMonitor :exec
UPDATE "monitor"
SET is_active = FALSE
WHERE id = $1
`

func (q *Queries) DisableMonitor(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, disableMonitor, id)
	return err
}

const enableMonitor = `-- name: EnableMonitor :exec
UPDATE "monitor"
SET is_active = TRUE
WHERE id = $1
`

func (q *Queries) EnableMonitor(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, enableMonitor, id)
	return err
}

const getAllMonitorsByTargetID = `-- name: GetAllMonitorsByTargetID :many
SELECT m.id, m.target_id, m.user_login, m.label, m.is_active, m.probe_interval_sec, m.expectations, m.current_status, m.last_evaluated_at, m.created_at, t.id, t.signature_hash, t.protocol, t.is_active, t.endpoint, t.network_config, t.probe_interval_sec, u.login, u.password_hash,
       COALESCE(
           (SELECT jsonb_agg(ac.*)
            FROM "alert_contact" ac
            JOIN "monitor_alert_contact" mac ON ac.id = mac.contact_id
            WHERE mac.monitor_id = m.id), '[]'::jsonb
       ) AS alert_contacts,
       COALESCE(
           (SELECT jsonb_agg(mw.*)
            FROM "maintenance_window" mw
            JOIN "maintenance_window_monitor" mwm ON mw.id = mwm.window_id
            WHERE mwm.monitor_id = m.id), '[]'::jsonb
       ) AS maintenance_windows
FROM "monitor" m
         JOIN "target" t ON m.target_id = t.id
         JOIN "user" u ON m.user_login = u.login
WHERE m.target_id = $1
`

type GetAllMonitorsByTargetIDRow struct {
	Monitor            Monitor     `json:"monitor"`
	Target             Target      `json:"target"`
	User               User        `json:"user"`
	AlertContacts      interface{} `json:"alert_contacts"`
	MaintenanceWindows interface{} `json:"maintenance_windows"`
}

func (q *Queries) GetAllMonitorsByTargetID(ctx context.Context, targetID pgtype.UUID) ([]GetAllMonitorsByTargetIDRow, error) {
	rows, err := q.db.Query(ctx, getAllMonitorsByTargetID, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllMonitorsByTargetIDRow
	for rows.Next() {
		var i GetAllMonitorsByTargetIDRow
		if err := rows.Scan(
			&i.Monitor.ID,
			&i.Monitor.TargetID,
			&i.Monitor.UserLogin,
			&i.Monitor.Label,
			&i.Monitor.IsActive,
			&i.Monitor.ProbeIntervalSec,
			&i.Monitor.Expectations,
			&i.Monitor.CurrentStatus,
			&i.Monitor.LastEvaluatedAt,
			&i.Monitor.CreatedAt,
			&i.Target.ID,
			&i.Target.SignatureHash,
			&i.Target.Protocol,
			&i.Target.IsActive,
			&i.Target.Endpoint,
			&i.Target.NetworkConfig,
			&i.Target.ProbeIntervalSec,
			&i.User.Login,
			&i.User.PasswordHash,
			&i.AlertContacts,
			&i.MaintenanceWindows,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMonitorsByUser = `-- name: GetAllMonitorsByUser :many
SELECT m.id, m.target_id, m.user_login, m.label, m.is_active, m.probe_interval_sec, m.expectations, m.current_status, m.last_evaluated_at, m.created_at, t.id, t.signature_hash, t.protocol, t.is_active, t.endpoint, t.network_config, t.probe_interval_sec, u.login, u.password_hash,
       COALESCE(
           (SELECT jsonb_agg(ac.*)
            FROM "alert_contact" ac
            JOIN "monitor_alert_contact" mac ON ac.id = mac.contact_id
            WHERE mac.monitor_id = m.id), '[]'::jsonb
       ) AS alert_contacts,
       COALESCE(
           (SELECT jsonb_agg(mw.*)
            FROM "maintenance_window" mw
            JOIN "maintenance_window_monitor" mwm ON mw.id = mwm.window_id
            WHERE mwm.monitor_id = m.id), '[]'::jsonb
       ) AS maintenance_windows
FROM "monitor" m
         JOIN "target" t ON m.target_id = t.id
         JOIN "user" u ON m.user_login = u.login
WHERE m.user_login = $1
`

type GetAllMonitorsByUserRow struct {
	Monitor            Monitor     `json:"monitor"`
	Target             Target      `json:"target"`
	User               User        `json:"user"`
	AlertContacts      interface{} `json:"alert_contacts"`
	MaintenanceWindows interface{} `json:"maintenance_windows"`
}

func (q *Queries) GetAllMonitorsByUser(ctx context.Context, userLogin string) ([]GetAllMonitorsByUserRow, error) {
	rows, err := q.db.Query(ctx, getAllMonitorsByUser, userLogin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllMonitorsByUserRow
	for rows.Next() {
		var i GetAllMonitorsByUserRow
		if err := rows.Scan(
			&i.Monitor.ID,
			&i.Monitor.TargetID,
			&i.Monitor.UserLogin,
			&i.Monitor.Label,
			&i.Monitor.IsActive,
			&i.Monitor.ProbeIntervalSec,
			&i.Monitor.Expectations,
			&i.Monitor.CurrentStatus,
			&i.Monitor.LastEvaluatedAt,
			&i.Monitor.CreatedAt,
			&i.Target.ID,
			&i.Target.SignatureHash,
			&i.Target.Protocol,
			&i.Target.IsActive,
			&i.Target.Endpoint,
			&i.Target.NetworkConfig,
			&i.Target.ProbeIntervalSec,
			&i.User.Login,
			&i.User.PasswordHash,
			&i.AlertContacts,
			&i.MaintenanceWindows,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonitorByID = `-- name: GetMonitorByID :one
SELECT m.id, m.target_id, m.user_login, m.label, m.is_active, m.probe_interval_sec, m.expectations, m.current_status, m.last_evaluated_at, m.created_at, t.id, t.signature_hash, t.protocol, t.is_active, t.endpoint, t.network_config, t.probe_interval_sec, u.login, u.password_hash,
       COALESCE(
           (SELECT jsonb_agg(ac.*)
            FROM "alert_contact" ac
            JOIN "monitor_alert_contact" mac ON ac.id = mac.contact_id
            WHERE mac.monitor_id = m.id), '[]'::jsonb
       ) AS alert_contacts,
       COALESCE(
           (SELECT jsonb_agg(mw.*)
            FROM "maintenance_window" mw
            JOIN "maintenance_window_monitor" mwm ON mw.id = mwm.window_id
            WHERE mwm.monitor_id = m.id), '[]'::jsonb
       ) AS maintenance_windows
FROM "monitor" m
         JOIN "target" t ON m.target_id = t.id
         JOIN "user" u ON m.user_login = u.login
WHERE m.id = $1
`

type GetMonitorByIDRow struct {
	Monitor            Monitor     `json:"monitor"`
	Target             Target      `json:"target"`
	User               User        `json:"user"`
	AlertContacts      interface{} `json:"alert_contacts"`
	MaintenanceWindows interface{} `json:"maintenance_windows"`
}

func (q *Queries) GetMonitorByID(ctx context.Context, id pgtype.UUID) (GetMonitorByIDRow, error) {
	row := q.db.QueryRow(ctx, getMonitorByID, id)
	var i GetMonitorByIDRow
	err := row.Scan(
		&i.Monitor.ID,
		&i.Monitor.TargetID,
		&i.Monitor.UserLogin,
		&i.Monitor.Label,
		&i.Monitor.IsActive,
		&i.Monitor.ProbeIntervalSec,
		&i.Monitor.Expectations,
		&i.Monitor.CurrentStatus,
		&i.Monitor.LastEvaluatedAt,
		&i.Monitor.CreatedAt,
		&i.Target.ID,
		&i.Target.SignatureHash,
		&i.Target.Protocol,
		&i.Target.IsActive,
		&i.Target.Endpoint,
		&i.Target.NetworkConfig,
		&i.Target.ProbeIntervalSec,
		&i.User.Login,
		&i.User.PasswordHash,
		&i.AlertContacts,
		&i.MaintenanceWindows,
	)
	return i, err
}

const getMonitorsToEvaluate = `-- name: GetMonitorsToEvaluate :many
SELECT m.id, m.target_id, m.user_login, m.label, m.is_active, m.probe_interval_sec, m.expectations, m.current_status, m.last_evaluated_at, m.created_at, t.id, t.signature_hash, t.protocol, t.is_active, t.endpoint, t.network_config, t.probe_interval_sec, u.login, u.password_hash,
       COALESCE(
           (SELECT jsonb_agg(ac.*)
            FROM "alert_contact" ac
            JOIN "monitor_alert_contact" mac ON ac.id = mac.contact_id
            WHERE mac.monitor_id = m.id), '[]'::jsonb
       ) AS alert_contacts,
       COALESCE(
           (SELECT jsonb_agg(mw.*)
            FROM "maintenance_window" mw
            JOIN "maintenance_window_monitor" mwm ON mw.id = mwm.window_id
            WHERE mwm.monitor_id = m.id), '[]'::jsonb
       ) AS maintenance_windows
FROM "monitor" m
         JOIN "target" t ON m.target_id = t.id
         JOIN "user" u ON m.user_login = u.login
WHERE m.is_active = TRUE
  AND m.last_evaluated_at + (m.probe_interval_sec * INTERVAL '1 second') <= NOW() at time zone 'Europe/Moscow' -- TODO: убрать
  AND m.target_id = ANY ($1::uuid[])
`

type GetMonitorsToEvaluateRow struct {
	Monitor            Monitor     `json:"monitor"`
	Target             Target      `json:"target"`
	User               User        `json:"user"`
	AlertContacts      interface{} `json:"alert_contacts"`
	MaintenanceWindows interface{} `json:"maintenance_windows"`
}

func (q *Queries) GetMonitorsToEvaluate(ctx context.Context, targetIds []pgtype.UUID) ([]GetMonitorsToEvaluateRow, error) {
	rows, err := q.db.Query(ctx, getMonitorsToEvaluate, targetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonitorsToEvaluateRow
	for rows.Next() {
		var i GetMonitorsToEvaluateRow
		if err := rows.Scan(
			&i.Monitor.ID,
			&i.Monitor.TargetID,
			&i.Monitor.UserLogin,
			&i.Monitor.Label,
			&i.Monitor.IsActive,
			&i.Monitor.ProbeIntervalSec,
			&i.Monitor.Expectations,
			&i.Monitor.CurrentStatus,
			&i.Monitor.LastEvaluatedAt,
			&i.Monitor.CreatedAt,
			&i.Target.ID,
			&i.Target.SignatureHash,
			&i.Target.Protocol,
			&i.Target.IsActive,
			&i.Target.Endpoint,
			&i.Target.NetworkConfig,
			&i.Target.ProbeIntervalSec,
			&i.User.Login,
			&i.User.PasswordHash,
			&i.AlertContacts,
			&i.MaintenanceWindows,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAlertContactFromMonitor = `-- name: RemoveAlertContactFromMonitor :exec
DELETE
FROM "monitor_alert_contact"
WHERE monitor_id = $1
  AND contact_id = $2
`

type RemoveAlertContactFromMonitorParams struct {
	MonitorID pgtype.UUID `json:"monitor_id"`
	ContactID pgtype.UUID `json:"contact_id"`
}

func (q *Queries) RemoveAlertContactFromMonitor(ctx context.Context, arg RemoveAlertContactFromMonitorParams) error {
	_, err := q.db.Exec(ctx, removeAlertContactFromMonitor, arg.MonitorID, arg.ContactID)
	return err
}

const updateMonitor = `-- name: UpdateMonitor :exec
UPDATE "monitor"
SET target_id          = $2,
    user_login         = $3,
    label              = $4,
    is_active          = $5,
    probe_interval_sec = $6,
    expectations       = $7,
    current_status     = $8,
    last_evaluated_at  = $9
WHERE id = $1
`

type UpdateMonitorParams struct {
	ID               pgtype.UUID      `json:"id"`
	TargetID         pgtype.UUID      `json:"target_id"`
	UserLogin        string           `json:"user_login"`
	Label            string           `json:"label"`
	IsActive         bool             `json:"is_active"`
	ProbeIntervalSec int32            `json:"probe_interval_sec"`
	Expectations     []byte           `json:"expectations"`
	CurrentStatus    StatusType       `json:"current_status"`
	LastEvaluatedAt  pgtype.Timestamp `json:"last_evaluated_at"`
}

func (q *Queries) UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) error {
	_, err := q.db.Exec(ctx, updateMonitor,
		arg.ID,
		arg.TargetID,
		arg.UserLogin,
		arg.Label,
		arg.IsActive,
		arg.ProbeIntervalSec,
		arg.Expectations,
		arg.CurrentStatus,
		arg.LastEvaluatedAt,
	)
	return err
}
