// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: probe_summary.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProbeSummaryByMonitorID = `-- name: GetProbeSummaryByMonitorID :many
SELECT m.id                         AS monitor_id,
       pr.latency_ms                AS latency_ms,
       pr.probe_time                AS probe_time,
       msl.status                   AS monitor_status,
       COALESCE(pr.status_code, 0)  AS status_code,
       pr.network_failure           AS network_failure,
       COALESCE(pr.error_message, '') AS failure_reason
FROM "probe_result" pr
         JOIN monitor m
              on m.target_id = pr.target_id
         JOIN monitor_status_log msl
              on m.id = msl.monitor_id
                  and msl.start_time <= pr.probe_time
                  and pr.probe_time < msl.end_time
WHERE m.id = $1
  and pr.processing_status = 'PROCESSED'
ORDER BY pr.probe_time DESC
LIMIT $2
`

type GetProbeSummaryByMonitorIDParams struct {
	ID    pgtype.UUID `json:"id"`
	Limit int32       `json:"limit"`
}

type GetProbeSummaryByMonitorIDRow struct {
	MonitorID      pgtype.UUID      `json:"monitor_id"`
	LatencyMs      int32            `json:"latency_ms"`
	ProbeTime      pgtype.Timestamp `json:"probe_time"`
	MonitorStatus  StatusType       `json:"monitor_status"`
	StatusCode     int32            `json:"status_code"`
	NetworkFailure bool             `json:"network_failure"`
	FailureReason  string           `json:"failure_reason"`
}

func (q *Queries) GetProbeSummaryByMonitorID(ctx context.Context, arg GetProbeSummaryByMonitorIDParams) ([]GetProbeSummaryByMonitorIDRow, error) {
	rows, err := q.db.Query(ctx, getProbeSummaryByMonitorID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProbeSummaryByMonitorIDRow
	for rows.Next() {
		var i GetProbeSummaryByMonitorIDRow
		if err := rows.Scan(
			&i.MonitorID,
			&i.LatencyMs,
			&i.ProbeTime,
			&i.MonitorStatus,
			&i.StatusCode,
			&i.NetworkFailure,
			&i.FailureReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProbeSummaryByMonitorIDForPeriod = `-- name: GetProbeSummaryByMonitorIDForPeriod :many
SELECT m.id                           AS monitor_id,
       pr.latency_ms                  AS latency_ms,
       pr.probe_time                  AS probe_time,
       msl.status                     AS monitor_status,
       COALESCE(pr.status_code, 0)    AS status_code,
       pr.network_failure             AS network_failure,
       COALESCE(pr.error_message, '') AS failure_reason
FROM "probe_result" pr
         JOIN monitor m
              ON m.target_id = pr.target_id
         JOIN monitor_status_log msl
              ON m.id = msl.monitor_id
                  AND msl.start_time <= pr.probe_time
                  AND pr.probe_time < msl.end_time
WHERE m.id = $1
  AND pr.processing_status = 'PROCESSED'
  AND pr.probe_time >= $2
  AND pr.probe_time <= $3
ORDER BY pr.probe_time DESC
`

type GetProbeSummaryByMonitorIDForPeriodParams struct {
	ID          pgtype.UUID      `json:"id"`
	ProbeTime   pgtype.Timestamp `json:"probe_time"`
	ProbeTime_2 pgtype.Timestamp `json:"probe_time_2"`
}

type GetProbeSummaryByMonitorIDForPeriodRow struct {
	MonitorID      pgtype.UUID      `json:"monitor_id"`
	LatencyMs      int32            `json:"latency_ms"`
	ProbeTime      pgtype.Timestamp `json:"probe_time"`
	MonitorStatus  StatusType       `json:"monitor_status"`
	StatusCode     int32            `json:"status_code"`
	NetworkFailure bool             `json:"network_failure"`
	FailureReason  string           `json:"failure_reason"`
}

func (q *Queries) GetProbeSummaryByMonitorIDForPeriod(ctx context.Context, arg GetProbeSummaryByMonitorIDForPeriodParams) ([]GetProbeSummaryByMonitorIDForPeriodRow, error) {
	rows, err := q.db.Query(ctx, getProbeSummaryByMonitorIDForPeriod, arg.ID, arg.ProbeTime, arg.ProbeTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProbeSummaryByMonitorIDForPeriodRow
	for rows.Next() {
		var i GetProbeSummaryByMonitorIDForPeriodRow
		if err := rows.Scan(
			&i.MonitorID,
			&i.LatencyMs,
			&i.ProbeTime,
			&i.MonitorStatus,
			&i.StatusCode,
			&i.NetworkFailure,
			&i.FailureReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
