// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: target.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTarget = `-- name: CreateTarget :exec
INSERT INTO "target" (id, signature_hash, protocol, endpoint, network_config, is_active, probe_interval_sec)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateTargetParams struct {
	ID               pgtype.UUID  `json:"id"`
	SignatureHash    string       `json:"signature_hash"`
	Protocol         ProtocolType `json:"protocol"`
	Endpoint         string       `json:"endpoint"`
	NetworkConfig    []byte       `json:"network_config"`
	IsActive         bool         `json:"is_active"`
	ProbeIntervalSec int32        `json:"probe_interval_sec"`
}

func (q *Queries) CreateTarget(ctx context.Context, arg CreateTargetParams) error {
	_, err := q.db.Exec(ctx, createTarget,
		arg.ID,
		arg.SignatureHash,
		arg.Protocol,
		arg.Endpoint,
		arg.NetworkConfig,
		arg.IsActive,
		arg.ProbeIntervalSec,
	)
	return err
}

const deleteTargetByID = `-- name: DeleteTargetByID :exec
DELETE
FROM "target"
WHERE id = $1
`

func (q *Queries) DeleteTargetByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTargetByID, id)
	return err
}

const disableTarget = `-- name: DisableTarget :exec
UPDATE "target"
SET is_active = FALSE
WHERE id = $1
`

func (q *Queries) DisableTarget(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, disableTarget, id)
	return err
}

const enableTarget = `-- name: EnableTarget :exec
UPDATE "target"
SET is_active = TRUE
WHERE id = $1
`

func (q *Queries) EnableTarget(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, enableTarget, id)
	return err
}

const getAllActiveTargets = `-- name: GetAllActiveTargets :many
SELECT id, signature_hash, protocol, is_active, endpoint, network_config, probe_interval_sec
FROM "target"
WHERE is_active = TRUE
`

func (q *Queries) GetAllActiveTargets(ctx context.Context) ([]Target, error) {
	rows, err := q.db.Query(ctx, getAllActiveTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Target
	for rows.Next() {
		var i Target
		if err := rows.Scan(
			&i.ID,
			&i.SignatureHash,
			&i.Protocol,
			&i.IsActive,
			&i.Endpoint,
			&i.NetworkConfig,
			&i.ProbeIntervalSec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTargetByHash = `-- name: GetTargetByHash :one
SELECT id, signature_hash, protocol, is_active, endpoint, network_config, probe_interval_sec
FROM "target"
WHERE signature_hash = $1
`

func (q *Queries) GetTargetByHash(ctx context.Context, signatureHash string) (Target, error) {
	row := q.db.QueryRow(ctx, getTargetByHash, signatureHash)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.SignatureHash,
		&i.Protocol,
		&i.IsActive,
		&i.Endpoint,
		&i.NetworkConfig,
		&i.ProbeIntervalSec,
	)
	return i, err
}

const getTargetByID = `-- name: GetTargetByID :one
SELECT id, signature_hash, protocol, is_active, endpoint, network_config, probe_interval_sec
FROM "target"
WHERE id = $1
`

func (q *Queries) GetTargetByID(ctx context.Context, id pgtype.UUID) (Target, error) {
	row := q.db.QueryRow(ctx, getTargetByID, id)
	var i Target
	err := row.Scan(
		&i.ID,
		&i.SignatureHash,
		&i.Protocol,
		&i.IsActive,
		&i.Endpoint,
		&i.NetworkConfig,
		&i.ProbeIntervalSec,
	)
	return i, err
}

const updateTarget = `-- name: UpdateTarget :exec
UPDATE "target"
SET signature_hash     = $2,
    protocol           = $3,
    endpoint           = $4,
    network_config     = $5,
    is_active          = $6,
    probe_interval_sec = $7
WHERE id = $1
`

type UpdateTargetParams struct {
	ID               pgtype.UUID  `json:"id"`
	SignatureHash    string       `json:"signature_hash"`
	Protocol         ProtocolType `json:"protocol"`
	Endpoint         string       `json:"endpoint"`
	NetworkConfig    []byte       `json:"network_config"`
	IsActive         bool         `json:"is_active"`
	ProbeIntervalSec int32        `json:"probe_interval_sec"`
}

func (q *Queries) UpdateTarget(ctx context.Context, arg UpdateTargetParams) error {
	_, err := q.db.Exec(ctx, updateTarget,
		arg.ID,
		arg.SignatureHash,
		arg.Protocol,
		arg.Endpoint,
		arg.NetworkConfig,
		arg.IsActive,
		arg.ProbeIntervalSec,
	)
	return err
}

const updateTargetProbeInterval = `-- name: UpdateTargetProbeInterval :exec
UPDATE "target"
SET probe_interval_sec = $2
WHERE id = $1
`

type UpdateTargetProbeIntervalParams struct {
	ID               pgtype.UUID `json:"id"`
	ProbeIntervalSec int32       `json:"probe_interval_sec"`
}

func (q *Queries) UpdateTargetProbeInterval(ctx context.Context, arg UpdateTargetProbeIntervalParams) error {
	_, err := q.db.Exec(ctx, updateTargetProbeInterval, arg.ID, arg.ProbeIntervalSec)
	return err
}
