// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlcgen

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO "user" (login, password_hash)
VALUES ($1, $2)
`

type CreateUserParams struct {
	Login        string `json:"login"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.Login, arg.PasswordHash)
	return err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT login, password_hash
FROM "user"
WHERE login = $1
`

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, login)
	var i User
	err := row.Scan(&i.Login, &i.PasswordHash)
	return i, err
}
