@startuml
skinparam linetype ortho
'left to right direction
namespace healthcheck {
    class "HealthChecker" << (S,Aquamarine) >> {
        + Run(ctx context.Context) error

    }
    class "HealthCheckerConfig" << (S,Aquamarine) >> {
        + WorkerCount int
        + TaskQueueSize int

    }
    interface "Prober"  {
        + Probe(ctx context.Context, target *domain.Target) (domain.ProbeResult, error)
    }
    class "ProberRegistry" << (S,Aquamarine) >> {
        + Register(protocol domain.Protocol, prober Prober) 
        + Get(protocol domain.Protocol) (Prober, error)
    }
    class "Scheduler" << (S,Aquamarine) >> {
        + Run(ctx context.Context) error

    }

    class "WorkerPool" << (S,Aquamarine) >> {
        + Run(ctx context.Context) 

    }
    class "scheduleEntry" << (S,Aquamarine) >> {
        + Target domain.Target
    }
}

enum "domain.Protocol" {
    HTTP
    TCP
    ICMP
}

struct domain.Target {
    + ID
    + Endpoint
    + Config
    + IsActive
    + ProbeIntervalSec
}
struct domain.ProbeResult {
    + ID
    + Target
    + LatencyMs
    + ProbeTime
    + NetworkFailure
    + StatusCode
    + Meta
    + ProcessingStatus
}

interface domain.ProbeResultRepository {
    + Create(probeResult *ProbeResult)
}

interface "domain.TargetRepository" {
    + Create(ctx context.Context, target *Target) (int64, error)
    + GetByID(ctx context.Context, id int64) (*Target, error)
    + GetAllActive(ctx context.Context) ([]Target, error)
    + Update(ctx context.Context, target *Target) error
    + DeleteByID(ctx context.Context, id int64) error
    + Disable(ctx context.Context, id int64) error
    + Enable(ctx context.Context, id int64) error
}

namespace repository {
    class "PostgresTargetRepository" implements "domain.TargetRepository"{
        + Create(ctx context.Context, target *domain.Target) (int64, error)
        + GetByID(ctx context.Context, id int64) (*domain.Target, error)
        + GetAllActive(ctx context.Context) ([]domain.Target, error)
        + Update(ctx context.Context, target *domain.Target) error
        + DeleteByID(ctx context.Context, id int64) error
        + Disable(ctx context.Context, id int64) error
        + Enable(ctx context.Context, id int64) error
    }

    class "PostgresProbeResultRepository" implements "domain.ProbeResultRepository" {
        + Create(probeResult *domain.ProbeResult)
    }
}

"healthcheck.HealthChecker" --> "domain.Target"
"healthcheck.HealthChecker" *-- "healthcheck.Scheduler"
"healthcheck.HealthChecker" *-- "healthcheck.WorkerPool"
"healthcheck.ProberRegistry" --> "domain.Protocol"
"healthcheck.ProberRegistry" o-- "healthcheck.Prober"
"healthcheck.Scheduler" --> "domain.Target"
"healthcheck.Scheduler" o-- "domain.TargetRepository"
"healthcheck.Scheduler" o-- "healthcheck.scheduleEntry"
"healthcheck.WorkerPool" o-- "domain.ProbeResultRepository"
"healthcheck.WorkerPool" --> "domain.Target"
"healthcheck.WorkerPool" o-- "healthcheck.ProberRegistry"
"healthcheck.scheduleEntry" o-- "domain.Target"
"HealthChecker" *-- "HealthCheckerConfig"
domain.Target --> "domain.Protocol"
"domain.TargetRepository" --> domain.Target
"domain.ProbeResultRepository" --> domain.ProbeResult
"domain.ProbeResult" o-- domain.Target
@enduml

